##some of the most fundamental concepts of tensor using TensorFlow:-

Going to cover:-
  * intro to tensors.
  * getting information from the tensors.
  * Manipulating tensors.
  * Tensos and NumPy.
  * Using @tf.function ( to speed up our regular python functions).
  * Using GPU with TensorFlow(or TPUs).
  * Exercise to try.

#intro to tensors.


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
#Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Checked the number of dimension of scalar tensors
scalar.ndim 

0

In [ ]:
# Create Vector of tensors

vector = tf.constant([10,3,4,5],)
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10,  3,  4,  5], dtype=int32)>

In [ ]:
#checked number of dimension of vector tensors
vector.ndim

1

In [ ]:
# create Matrix
matrix= tf.constant([[3,5,9,6],[6,6,4,6]])
matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[3, 5, 9, 6],
       [6, 6, 4, 6]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create Tensors
tensor= tf.constant([[[1,2,3],
                    [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
#Checked number of dimension of  tensors
tensor.ndim

3

##Conclusion On creating Tensors with Constant.
   * scalar: a single number
   * vector : a number with direction
   * matrix: a 2-dimension array of  numbers
   * Tensor:  an n-dimensional array of number 

###Creating Tensors with tf.variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
# create same tensor with tf.variable() as above

changeable_tensor=tf.Variable([2,3,4])
unchangeable_tensor=tf.constant([2,3,4])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0]=7

TypeError: ignored

In [ ]:
# try with .assign()
changeable_tensor[1].assign(7)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([2, 7, 4], dtype=int32)>

In [ ]:
unchangeable_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [ ]:
## Let's try change one of the elements in our changeable tensor
unchangeable_tensor[0]=7

TypeError: ignored

In [ ]:
# try with .assign()
unchangeable_tensor[1].assign(7)
unchangeable_tensor

AttributeError: ignored

# Creating Random tensor using TensorFlow

In [ ]:
# create two random (but the same)  tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2= random_2.normal(shape=(3,2))

In [ ]:
# Are They equal?
random_1,random_2,random_2==random_1

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
# shuffle tensor(a valuable  for when we want  t shuffle the data so the inherent order doesn't effect learning)

not_shuffled= tf.random.shuffle([[1,3],
                                 [4,5],
                                 [6,9]])

In [ ]:

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 9],
       [1, 3],
       [4, 5]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[6, 9],
       [1, 3],
       [4, 5]], dtype=int32)>

### Creating tensor form  NumPy array
* **Main difference between NumPy arrays and TensorFlow tensors is that  tensors can  be run on GPU (much faster for numerical computing)**

In [ ]:
# create tensor of all ones

tf.ones([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensor of all zeros
import numpy as np
a=tf.zeros(shape=(3,5),dtype =np.int32)
a

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
# Convert  NumPy arrays to tensors

import numpy as np

numpy_A=np.arange(1,21,dtype = np.int32)
numpy_A
type(numpy_A)

numpy.ndarray

In [ ]:
a = tf.constant(numpy_A, shape=(2,5,2))
a


<tf.Tensor: shape=(2, 5, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]], dtype=int32)>

In [ ]:
a.ndim

3

### Indexing and Expanding tensors:

In [ ]:

# create 4 dimension tensors

dim_4 = tf.zeros(shape=(2,3,6,4))
dim_4

<tf.Tensor: shape=(2, 3, 6, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0.

In [ ]:
dim_4.ndim

4

In [ ]:
# to get the first 2 element of each dimension from tensor 

dim_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
dim_4[:2,:2]

<tf.Tensor: shape=(2, 2, 6, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first  element from  each index  except from the last   on element of the tensor
dim_4[:1,:1,:1,:]

# dim_4


<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create 2 dim tensor 

dim_2 = tf.constant([[10,7],
                     [2,4]])
dim_2


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  4]], dtype=int32)>

In [ ]:
dim_2.shape ,dim_2.ndim ,

(TensorShape([2, 2]), 2)

In [ ]:
# to get the last item from each rows from the 2 dim tensor
dim_2[:,-1] , 

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>,)

In [ ]:
dim_2[:,1] 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
dim_2 , dim_2.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 2,  4]], dtype=int32)>, TensorShape([2, 2]))

In [ ]:
# Add extra Dimension to the 2 dim tensor

new_dim= dim_2[...,tf.newaxis]
new_dim , new_dim.ndim

(<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 2],
         [ 4]]], dtype=int32)>, 3)

In [ ]:

new_dim

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternate  of tf.newaxis to add newdimension

new_dim2 = tf.expand_dims(dim_2,axis=-1)
new_dim2

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 4]]], dtype=int32)>

In [ ]:
new_dim2.ndim

3

In [ ]:
new_dim3 = tf.expand_dims(new_dim,axis=-1)
new_dim3

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 7]]],


       [[[ 2]],

        [[ 4]]]], dtype=int32)>

In [ ]:
new_dim3.ndim

4

In [ ]:
# Expand the 0-axis of the dimension 
new_dim4 = tf.expand_dims(dim_2,axis=0)
new_dim4

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  4]]], dtype=int32)>

### Manipulating tensor(tensor Operations)
**Basics Operations:-
 * Adding(+)
 * Substract(-)
 * Multiply(*)
 * Divide(/)**


 

In [ ]:
# adding value to the tensor using  addition operator

tensor =  tf.constant([[2,5],[8,4]],dtype=np.float16)
print("Actual tensor:" , tensor)
added_tensor = tensor +23
print("Add 23 to each item of the Actual tensor :",added_tensor)


Actual tensor: tf.Tensor(
[[2. 5.]
 [8. 4.]], shape=(2, 2), dtype=float16)
Add 23 to each item of the Actual tensor : tf.Tensor(
[[25. 28.]
 [31. 27.]], shape=(2, 2), dtype=float16)


In [ ]:
# adding value to the tensor using  substraction  operator

sub_tensor = added_tensor-4.5

print("Added tensor:" , added_tensor)
print("sub 4.5 to each item of the added_tensor :",sub_tensor)

Added tensor: tf.Tensor(
[[25. 28.]
 [31. 27.]], shape=(2, 2), dtype=float16)
sub 4.5 to each item of the added_tensor : tf.Tensor(
[[20.5 23.5]
 [26.5 22.5]], shape=(2, 2), dtype=float16)


In [ ]:
# Using tensorFlow built-in fucntion too

tf.multiply(tensor,3)


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 6., 15.],
       [24., 12.]], dtype=float16)>

In [ ]:
a = tensor*4
a

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 8., 20.],
       [32., 16.]], dtype=float16)>

In [ ]:
# Divide operation in tesnor

tf.divide(a,6)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1.333, 3.334],
       [5.332, 2.666]], dtype=float16)>

### Matrix Multiplication with tensor

**In machine learning, matrix multiplication  is one of the most common  tensor operations.**

**There are two rules  our tensor(or matrices) need to  fulfil  if we  going  to matrix multiply  them:-** 
 1. The inner dimension must be matches.
 2. The resulting  matrix  has the  shape of the outer  dimensions.

In [ ]:
tensor



<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[2., 5.],
       [8., 4.]], dtype=float16)>

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[44., 30.],
       [48., 56.]], dtype=float16)>

In [ ]:
tensor,tensor

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[2., 5.],
        [8., 4.]], dtype=float16)>,
 <tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[2., 5.],
        [8., 4.]], dtype=float16)>)

In [ ]:
tensor*tensor # multiply each item with specific index.

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 4., 25.],
       [64., 16.]], dtype=float16)>

In [ ]:
# Matrix multiplication  with Python operator "@"

tensor @ tensor # dot product of 2 matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[44., 30.],
       [48., 56.]], dtype=float16)>

In [ ]:
# Create tensor for shape(3,2)

x = tf.constant([[2,4],[3,6],[8,2]])
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 4],
       [3, 6],
       [8, 2]], dtype=int32)>

In [ ]:
y = tf.constant([[2,8],[9,6],[5,2]])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 8],
       [9, 6],
       [5, 2]], dtype=int32)>

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [3, 6],
        [8, 2]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 8],
        [9, 6],
        [5, 2]], dtype=int32)>)

In [ ]:
# change the shape of x to shape(2,3) from (3,2)
sh = tf.reshape(x,shape= (2,3))
x, sh

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [3, 6],
        [8, 2]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 4, 3],
        [6, 8, 2]], dtype=int32)>)

In [ ]:
# multiply the tensor
y@ tf.reshape(x,shape= (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[52, 72, 22],
       [54, 84, 39],
       [22, 36, 19]], dtype=int32)>

In [ ]:
# transpose of x and keep in z varialble then after multiply y@z tensors.
z= tf.transpose(x)
x,z

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [3, 6],
        [8, 2]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 3, 8],
        [4, 6, 2]], dtype=int32)>)

In [ ]:
y @ z

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[36, 54, 32],
       [42, 63, 84],
       [18, 27, 44]], dtype=int32)>

In [ ]:
tf.matmul(y,z)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[36, 54, 32],
       [42, 63, 84],
       [18, 27, 44]], dtype=int32)>

##**The dot Products**
**Matrix  multiplication is also refer to dot product.**

**perform multiplication by using :-**
  * **tf.matmul()**
  * **tf.tensordot()**
  * **@**

In [ ]:
#perform dot product  on x and y (required transpose of x or y)

x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 4],
        [3, 6],
        [8, 2]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 8],
        [9, 6],
        [5, 2]], dtype=int32)>)

In [ ]:
# using by transpose  of y tensor and multiply them
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[36, 42, 18],
       [54, 63, 27],
       [32, 84, 44]], dtype=int32)>

In [ ]:
# using byr reshape to (2,3) from tensor(3,2) in y matrix and multiply them.
tf.matmul(x,tf.reshape(y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[28, 36, 26],
       [42, 54, 39],
       [28, 74, 76]], dtype=int32)>

## Changing the Datatype of tensor

In [ ]:
# Default DataType is int32 for integer
a = tf.constant([2,5,3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 5, 3], dtype=int32)>

In [ ]:
# Casting Data by using cast() function as per need of bit precission.

tf.cast(a,dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([2, 5, 3], dtype=int16)>

In [ ]:
# Default DataType is float32 for interger
b = tf.constant([10,5.,39])
b

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([10.,  5., 39.], dtype=float32)>

In [ ]:
# Casting Data by using cast() function as per need of bit precission.
tf.cast(b,dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([10,  5, 39], dtype=int16)>

### Aggregating tensors
  * **Aggregate tensrs = condensing them from the multiple values down to a ** **smaller  amount of values**.

In [ ]:
  # Get the absolute values

tns=tf.constant([-7,-10])
print("Original tensor",tns)
print("Absolute Value of tns tensor ",tf.abs(tns))

Original tensor tf.Tensor([ -7 -10], shape=(2,), dtype=int32)
Absolute Value of tns tensor  tf.Tensor([ 7 10], shape=(2,), dtype=int32)


###Let's go through  the following  forms of Aggregation 
  * Get the minimum
  * Get the maximum
  * Get the mean of a tensor
  * Get the sum of a tensor

In [ ]:
# Create a random tensor with the value between 0 and 100 of size 50

ag = tf.constant(np.random.randint(1,100,size=50))
ag

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([96,  4, 29, 56, 93, 22, 99, 98, 75, 98, 57,  9, 78, 83, 68, 60, 63,
       55, 29, 24, 69, 25, 70, 25, 19, 44, 22, 53, 36, 35, 97,  2, 31, 61,
       50, 27, 49, 14, 91, 22, 85, 92, 33, 59,  2, 40,  5, 48,  8, 17])>

In [ ]:
# getting minimum value
tf.reduce_min(ag)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# getting maximum value
tf.reduce_max(ag)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# get mean value

tf.reduce_mean(ag)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
#get sum of the tensor
tf.reduce_sum(ag)


<tf.Tensor: shape=(), dtype=int64, numpy=2427>

In [ ]:
# Variance of the tesor.

import tensorflow_probability as tfp
tfp.stats.variance(tf.cast(ag, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=887.20844>

In [ ]:
# tf.cast(ag,dtype=tf.float32)

In [ ]:
#standard deviation of tensor
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_std(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.1180339>

In [ ]:
tfp.stats.stddev(x, sample_axis=0, keepdims=False, name=None)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

### Finding the positon of maximum and minimum

In [ ]:
a = tf.random.uniform(shape=[50])
a

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find the position of maximum
tf.argmax(a)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# value of the max at that position
a[tf.argmax(a)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
## find the position of minimum
tf.argmin(a)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# value of the min at that position
a[tf.argmin(a)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
c = tf.constant(tf.random.uniform(shape=[50]) , shape=(1,1,1,1,50)) 

In [ ]:
c.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
#Squeeze  a tensor

c_squeeze = tf.squeeze(c)
c_squeeze





<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
print("Original Shape :",c.shape)
print("Squeezed Shape :",c_squeeze.shape)

Original Shape : (1, 1, 1, 1, 50)
Squeezed Shape : (50,)


### One-hot encoding

In [ ]:
# create a list of indices
ls = [0,1,2,3,4]

#one hot encode our list
tf.one_hot(ls , depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# custom values for one hot encode

tf.one_hot(ls , depth=5 , on_value="Hi" , off_value= "How are you")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Hi', b'How are you', b'How are you', b'How are you',
        b'How are you'],
       [b'How are you', b'Hi', b'How are you', b'How are you',
        b'How are you'],
       [b'How are you', b'How are you', b'Hi', b'How are you',
        b'How are you'],
       [b'How are you', b'How are you', b'How are you', b'Hi',
        b'How are you'],
       [b'How are you', b'How are you', b'How are you', b'How are you',
        b'Hi']], dtype=object)>

### Squaring , logging and Square-root


In [ ]:
# create a new tensor

h = tf.range(1,15)
print("Tensor" , h)

Tensor tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14], shape=(14,), dtype=int32)


In [ ]:
# Square a tensor

tf.square(h)

<tf.Tensor: shape=(14,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196], dtype=int32)>

In [ ]:
# square root
tf.sqrt(tf.cast(h , dtype=tf.float32))

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       , 3.1622777, 3.3166246, 3.4641016,
       3.6055512, 3.7416573], dtype=float32)>

In [ ]:
# log of tensor

tf.math.log(tf.cast(h , dtype=tf.float32))

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574], dtype=float32)>

### Tensor and NumPy
  * TensorFlow interacts beautifully with NumPy arrays.

In [ ]:
# Create tensor directly from the NumPy arrays
tn =  tf.constant(np.array([2,4,5,6]))
tn , type(tn)

(<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 4, 5, 6])>,
 tensorflow.python.framework.ops.EagerTensor)

In [ ]:
# convert back tensor to the NumPy arrays

np.array(tn) , type(np.array(tn))

(array([2, 4, 5, 6]), numpy.ndarray)

In [ ]:
type(tn)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
arr = tn.numpy()
arr , type(arr)

(array([2, 4, 5, 6]), numpy.ndarray)

In [ ]:
tf.constant(arr)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 4, 5, 6])>

In [ ]:
# The Default types of each  are  slightly different 

nump = tf.constant(np.array([2,.7,.9,9.]))
tens = tf.constant([2.,54,7,8])

nump ,  tens

(<tf.Tensor: shape=(4,), dtype=float64, numpy=array([2. , 0.7, 0.9, 9. ])>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2., 54.,  7.,  8.], dtype=float32)>)

In [ ]:
# Checking Datatype(dtype) of each

nump.dtype , tens.dtype

(tf.float64, tf.float32)

## Finding access to GPUs

In [ ]:
import tensorflow as tf

In [ ]:
tf.config.list_physical_devices()


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
# to check the CPU and GPU name with Memory and also give CUDA version 
!nvidia-smi

Mon Jun 13 08:52:11 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    31W /  70W |    432MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

 Note:- If you have access to a CUDA enabled GPU ,TensorFlow will  automatically  use it whenever possible

In [1]:
import tensorflow as tf

In [15]:

a = tf.Variable([[2,5,7],[3,7,9]])
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 5, 7],
       [3, 7, 9]], dtype=int32)>

In [16]:
a[1:,1]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([7], dtype=int32)>

In [18]:
a

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 5, 7],
       [3, 7, 9]], dtype=int32)>

In [19]:
a[1:,1].assign([5])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[2, 5, 7],
       [3, 5, 9]], dtype=int32)>

In [ ]:
changeable_tensor[1].assign(7)